const C = {
  SET_TIP: 'SET_TIP',
  SET_SPLIT: 'SET_SPLIT',
  SET_BILL: 'SET_BILL',
  SET_RESULT: 'SET_RESULT',
  SET_ROUTE: 'SET_ROUTE',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SET_MOOD: 'SET_MOOD',
  OPEN_VENMO: 'OPEN_VENMO',
}

export default C;